# How to get coordinate of closest point to both lines

Let's found point which has same distance to the lines

We have 2 points of first line `A`, `B`. And two points of the second line `C`, `D`

In [77]:
from sympy import symbols
from sympy import sqrt, simplify, solve, Eq, expand
import numpy as np
from IPython.display import display
import re

line points

In [78]:
i, j, k = symbols("i j k")


def get_coordinates(label):
    return sum([i * symbols(label + "_" + v) for i, v in zip([i, j, k], "xyz")])


def vec_to_ijk(vec):
    return sum([i * v for i, v in zip([i, j, k], vec)])


def ijk_to_vec(ijk):
    return np.array(
        [
            ijk.subs({i: 1, j: 0, k: 0}),
            ijk.subs({i: 0, j: 1, k: 0}),
            ijk.subs({i: 0, j: 0, k: 1}),
        ]
    )


a = get_coordinates("a")
assert vec_to_ijk(ijk_to_vec(a)) == a
a

a_x*i + a_y*j + a_z*k

In [79]:
a = get_coordinates("a")
b = get_coordinates("b")
c = get_coordinates("c")
d = get_coordinates("d")
a + b + c + d

a_x*i + a_y*j + a_z*k + b_x*i + b_y*j + b_z*k + c_x*i + c_y*j + c_z*k + d_x*i + d_y*j + d_z*k

# Same distance

Searching coordinates

In [ ]:
point = np.array(symbols("x y z"))
point

array([x, y, z], dtype=object)

## Solution
Let's define line r as 
$$ \overline{r} = \overline{r_0} + t \overline{p}$$

in this case $\overline{r_0}$ - point `A`(translation) and $\overline{p}$ - point `A` - `B` (diraction)

We have point `point`. Put pendicular on the line and then draw a parallelogram with edges $\overline{p}$ and $\overline{A} - \overline{point}$

Area is `d` * $|\overline{p}|$ where `d` is distance
And area is $|\overline{A}-\overline{point}|*|\overline{p}|*sin(\alpha)=|(\overline{A}-\overline{point})\times (\overline{p})|$

So

$$
d = \dfrac{|(\overline{A}-\overline{point})\times (\overline{p})|}{|(\overline{p})|}
$$

$\overline{p}$ is `A` - `B`

In [55]:
def norm(vec):
    return sqrt(sum([i**2 for i in vec]))

In [ ]:
def get_distance(point_a, point_b, point_x):
    p = point_a - point_b
    return norm(np.cross((point_a - point_x), p)) / norm(p)

In [68]:
d1 = get_distance(a, b, point)
str(d1)

'sqrt((-(a_x - b_x)*(a_y - y) + (a_x - x)*(a_y - b_y))**2 + ((a_x - b_x)*(a_z - z) - (a_x - x)*(a_z - b_z))**2 + (-(a_y - b_y)*(a_z - z) + (a_y - y)*(a_z - b_z))**2)/sqrt((a_x - b_x)**2 + (a_y - b_y)**2 + (a_z - b_z)**2)'

In [70]:
d2 = get_distance(c, d, point)
str(d2)

'sqrt((-(c_x - d_x)*(c_y - y) + (c_x - x)*(c_y - d_y))**2 + ((c_x - d_x)*(c_z - z) - (c_x - x)*(c_z - d_z))**2 + (-(c_y - d_y)*(c_z - z) + (c_y - y)*(c_z - d_z))**2)/sqrt((c_x - d_x)**2 + (c_y - d_y)**2 + (c_z - d_z)**2)'

In [59]:
d1 - d2

-sqrt((-(c_x - d_x)*(c_y - y) + (c_x - x)*(c_y - d_y))**2 + ((c_x - d_x)*(c_z - z) - (c_x - x)*(c_z - d_z))**2 + (-(c_y - d_y)*(c_z - z) + (c_y - y)*(c_z - d_z))**2)/sqrt((c_x - d_x)**2 + (c_y - d_y)**2 + (c_z - d_z)**2) + sqrt((-(a_x - b_x)*(a_y - y) + (a_x - x)*(a_y - b_y))**2 + ((a_x - b_x)*(a_z - z) - (a_x - x)*(a_z - b_z))**2 + (-(a_y - b_y)*(a_z - z) + (a_y - y)*(a_z - b_z))**2)/sqrt((a_x - b_x)**2 + (a_y - b_y)**2 + (a_z - b_z)**2)

In [ ]:
solve(Eq(d1 - d2, 0), (point[0], point[1], point[2]))

KeyboardInterrupt: 

# Use vectors

In [24]:
h = get_coordinates("h")
_h = ijk_to_vec(h)

t1, t2 = symbols("t_1 t_2")

In [304]:
ab = a - b
cd = c - d

p1 = a + (a - b) * t1
p2 = d + (d - c) * t2

## vec H || [AB, CD]

In [306]:
eq1 = vec_to_ijk(np.cross(ijk_to_vec(h), np.cross(ijk_to_vec(ab), ijk_to_vec(cd))))

eqs1 = [ijk_to_vec(eq1)[i] for i in range(3)]

print("System")
for eq in eqs1:
    display(Eq(eq, 0))

System


Eq(h_y*((a_x - b_x)*(c_y - d_y) - (a_y - b_y)*(c_x - d_x)) - h_z*(-(a_x - b_x)*(c_z - d_z) + (a_z - b_z)*(c_x - d_x)), 0)

Eq(-h_x*((a_x - b_x)*(c_y - d_y) - (a_y - b_y)*(c_x - d_x)) + h_z*((a_y - b_y)*(c_z - d_z) - (a_z - b_z)*(c_y - d_y)), 0)

Eq(h_x*(-(a_x - b_x)*(c_z - d_z) + (a_z - b_z)*(c_x - d_x)) - h_y*((a_y - b_y)*(c_z - d_z) - (a_z - b_z)*(c_y - d_y)), 0)

In [307]:
def str_to_eq(s):
    s = '(' + s.replace(" ", "") + ')'
    return re.sub("_(\w)", r"_{\1}", s)

In [308]:
koef_matrix = list()

for eq in eqs1:
    koef_matrix.append([0] * 3)

    for i in range(3):
        tmp = eq.subs({_h[j]: int(j == i) for j in range(3)})
        if tmp == 0:
            koef_matrix[-1][i] = 0
            continue
        
        koef_matrix[-1][i] = symbols(
            str_to_eq(str(tmp))
        )
koef_matrix = np.array(koef_matrix)

eqs1 = list()
for row in koef_matrix:
    eqs1.append(row.dot(_h))

eqs1 = np.array(eqs1)
print("System")
for eq in eqs1:
    display(Eq(eq, 0))

System


Eq(((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*h_y + ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*h_z, 0)

Eq(((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*h_z + (-(a_{x}-b_{x})*(c_{y}-d_{y})+(a_{y}-b_{y})*(c_{x}-d_{x}))*h_x, 0)

Eq((-(a_{x}-b_{x})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{x}-d_{x}))*h_x + (-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*h_y, 0)

In [309]:
eqs2 = [ijk_to_vec(p2 - p1 - h)[i] for i in range(3)]

In [310]:
eqs = list(eqs1) + list(eqs2)

print("System")
for eq in eqs:
    display(eq)

System


((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*h_y + ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*h_z

((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*h_z + (-(a_{x}-b_{x})*(c_{y}-d_{y})+(a_{y}-b_{y})*(c_{x}-d_{x}))*h_x

(-(a_{x}-b_{x})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{x}-d_{x}))*h_x + (-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*h_y

-a_x*i + d_x*i - h_x*i - t_1*(a_x*i - b_x*i) + t_2*(-c_x*i + d_x*i)

-a_x*i - a_y + d_x*i + d_y - h_x*i - h_y - t_1*(a_x*i + a_y - b_x*i - b_y) + t_2*(-c_x*i - c_y + d_x*i + d_y)

-a_x*i - a_z + d_x*i + d_z - h_x*i - h_z - t_1*(a_x*i + a_z - b_x*i - b_z) + t_2*(-c_x*i - c_z + d_x*i + d_z)

In [312]:
res = solve(eqs[1:], [*_h, t1, t2])
res

{h_x: (((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*b_y*c_z - ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*b_y*d_z - ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*b_z*c_y + ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*b_z*d_y + ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*c_y*d_z - ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*c_z*d_y - ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c_{z}-d_{z})+(a_{z}-b_{z})*(c_{y}-d_{y}))*a_y*b_x*c_z + ((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-(a_{y}-b_{y})*(c

In [313]:
htt = [solve(eqs[i + 3], [_h[i]])[0] for i in range(3)]
[display(Eq(htt[i], _h[i])) for i in range(3)]
None

Eq(-a_x*t_1 - a_x + b_x*t_1 - c_x*t_2 + d_x*t_2 + d_x, h_x)

Eq(-a_x*i*t_1 - a_x*i - a_y*t_1 - a_y + b_x*i*t_1 + b_y*t_1 - c_x*i*t_2 - c_y*t_2 + d_x*i*t_2 + d_x*i + d_y*t_2 + d_y - h_x*i, h_y)

Eq(-a_x*i*t_1 - a_x*i - a_z*t_1 - a_z + b_x*i*t_1 + b_z*t_1 - c_x*i*t_2 - c_z*t_2 + d_x*i*t_2 + d_x*i + d_z*t_2 + d_z - h_x*i, h_z)

In [314]:
eqtt = [eqs[i].subs({_h[i]: htt[i] for i in range(3)}) for i in range(2)]
[display(i) for i in eqtt]
None

((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*(-a_x*i*t_1 - a_x*i - a_y*t_1 - a_y + b_x*i*t_1 + b_y*t_1 - c_x*i*t_2 - c_y*t_2 + d_x*i*t_2 + d_x*i + d_y*t_2 + d_y - h_x*i) + ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*(-a_x*i*t_1 - a_x*i - a_z*t_1 - a_z + b_x*i*t_1 + b_z*t_1 - c_x*i*t_2 - c_z*t_2 + d_x*i*t_2 + d_x*i + d_z*t_2 + d_z - h_x*i)

((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-a_x*i*t_1 - a_x*i - a_z*t_1 - a_z + b_x*i*t_1 + b_z*t_1 - c_x*i*t_2 - c_z*t_2 + d_x*i*t_2 + d_x*i + d_z*t_2 + d_z - h_x*i) + (-(a_{x}-b_{x})*(c_{y}-d_{y})+(a_{y}-b_{y})*(c_{x}-d_{x}))*(-a_x*t_1 - a_x + b_x*t_1 - c_x*t_2 + d_x*t_2 + d_x)

In [315]:
main_eq = eqtt[1].subs({t1: solve(eqtt[0], [t1])[0]})
main_eq

((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*(-a_x*i - a_x*i*(-((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*a_x*i - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*a_y - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*c_x*i*t_2 - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*c_y*t_2 + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*d_x*i*t_2 + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*d_x*i + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*d_y*t_2 + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*d_y - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*h_x*i - ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*a_x*i - ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*a_z - ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*c_x*i*t_2 - ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x}))*c_z*t_2 + ((a_{x}-b_{x})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{x}-d_{x

In [316]:
res = solve(main_eq, [t2])

In [317]:
res[0]

(-((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*b_y*i + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*b_z*i + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*d_y*i - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_x*d_z*i + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_y*b_x*i + ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_y*b_z - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_{y}-d_{y}))*a_y*d_x*i - ((a_{x}-b_{x})*(c_{y}-d_{y})-(a_{y}-b_{y})*(c_{x}-d_{x}))*((a_{y}-b_{y})*(c_{z}-d_{z})-(a_{z}-b_{z})*(c_

## By hand

In [80]:
ab = a - b
cd = c - d
t_list = symbols(' '.join(["T_"+str(i) for i in range(0, 7)]))
t_list

(T_0, T_1, T_2, T_3, T_4, T_5, T_6)

In [81]:
eq = ab * (t1 * t_list[1] + t2 * t_list[2] + t_list[3]) + cd* (t1 * t_list[4] + t2 * t_list[5] + t_list[6])

In [83]:
res = solve(ijk_to_vec(eq), [t1, t2])
res

{t_1: (T_2*T_6 - T_3*T_5)/(T_1*T_5 - T_2*T_4),
 t_2: (-T_1*T_6 + T_3*T_4)/(T_1*T_5 - T_2*T_4)}

## Check

In [84]:
import plotly.express as px

In [120]:
a_value = np.array([1.7, 1, 4.1])
b_value = np.array([2, -0.2, 1.8])
c_value = np.array([-2, -1.15, -0.7])
d_value = np.array([-1.2, -0.9, -0.65])

In [121]:
for k, v in res.items():
    print(k)
    display(v)

t_1


(T_2*T_6 - T_3*T_5)/(T_1*T_5 - T_2*T_4)

t_2


(-T_1*T_6 + T_3*T_4)/(T_1*T_5 - T_2*T_4)

In [122]:
list_t = np.array([
    0,
    -(a_value-b_value).dot(c_value-d_value),
    (d_value-c_value).dot(c_value-d_value),
    (d_value-a_value).dot(c_value-d_value),
    -(a_value-b_value).dot(a_value-b_value),
    (d_value-c_value).dot(a_value-b_value),
    (d_value-a_value).dot(a_value-b_value),
])

list_t

array([  0.    ,   0.175 ,  -0.705 ,   3.0325,  -6.82  ,   0.175 ,
       -12.335 ])

In [123]:
res_t = list()

for k, v in res.items():
    res_t.append(v.subs({k:v for k,v in zip(t_list, list_t)}))
    print(k, '=', res_t[-1])

t_1 = -1.70916383654546
t_2 = 3.87715791291425


In [124]:
p2_value = d_value+(d_value-c_value)*res_t[1]
p1_value = a_value+(a_value-b_value)*res_t[0]
p1_value, p2_value, (p1_value + p2_value) / 2

(array([2.21274915096364, -1.05099660385455, 0.168923175945452],
       dtype=object),
 array([1.90172633033140, 0.0692894782285615, -0.456142104354288],
       dtype=object),
 array([2.05723774064752, -0.490853562812992, -0.143609464204418],
       dtype=object))

In [125]:
points = np.array([
    a_value,
    b_value,
    c_value,
    d_value,
    p1_value,
    p2_value,
    (p1_value + p2_value) / 2
]).astype(np.float32)

color = np.array([
    0,0,0,0,1,1, 2
])

fig = px.scatter_3d(x=points[:, 0], y=points[:,1], z=points[:,2], color=color)
fig.show()

In [126]:
for k, v in res.items():
    print(k)
    print(v)

t_1
(T_2*T_6 - T_3*T_5)/(T_1*T_5 - T_2*T_4)
t_2
(-T_1*T_6 + T_3*T_4)/(T_1*T_5 - T_2*T_4)


In [135]:
def get_closest_point_and_dist(line1_p1, line1_p2, line2_p1, line2_p2):
    list_t = np.array(
        [
            0,
            -(line1_p1 - line1_p2).dot(line2_p1 - line2_p2),
            (line2_p2 - line2_p1).dot(line2_p1 - line2_p2),
            (line2_p2 - line1_p1).dot(line2_p1 - line2_p2),
            -(line1_p1 - line1_p2).dot(line1_p1 - line1_p2),
            (line2_p2 - line2_p1).dot(line1_p1 - line1_p2),
            (line2_p2 - line1_p1).dot(line1_p1 - line1_p2),
        ]
    )

    t1 = (list_t[2] * list_t[6] - list_t[3] * list_t[5]) / (
        list_t[1] * list_t[5] - list_t[2] * list_t[4]
    )
    t2 = (-list_t[1] * list_t[6] + list_t[3] * list_t[4]) / (
        list_t[1] * list_t[5] - list_t[2] * list_t[4]
    )

    p2_value = line2_p2 + (line2_p2 - line2_p1) * t2
    p1_value = line1_p1 + (line1_p1 - line1_p2) * t1
    return (p1_value + p2_value) / 2, np.linalg.norm(p2_value - p1_value)

def_res = get_closest_point_and_dist(
    a_value,
    b_value,
    c_value,
    d_value    
)

assert np.linalg.norm((def_res[0] - (p1_value + p2_value) / 2).astype(np.float32)) < 1e-10

def_res

(array([ 2.05723774, -0.49085356, -0.14360946]), 1.3200313273931596)

4.9960036e-16